<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["conductores", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
<h1><center>Editar Conductores</center></h1>
</div>

<?php echo $this->getContent(); ?>

<form action="http://localhost:8000/conductores/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "size" => 30, "class" => "form-control", "id" => "fieldId"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombre" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre", "size" => 30, "class" => "form-control", "id" => "fieldNombre"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEstado" class="col-sm-2 control-label">Estado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["estado", "type" => "number", "class" => "form-control", "id" => "fieldEstado"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVehiculoplaca" class="col-sm-2 control-label">Vehiculoplaca</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["vehiculoplaca", "size" => 30, "class" => "form-control", "id" => "fieldVehiculoplaca"]); ?>
    </div>
</div>

    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-success"]) ?>
        </div>
    </div>
</form>
