<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Buscar Conductores</h1>
    <p><?php echo $this->tag->linkTo(["conductores/new", "Create conductores"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "size" => 30, "class" => "form-control", "id" => "fieldId"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombre" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre", "size" => 30, "class" => "form-control", "id" => "fieldNombre"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEstado" class="col-sm-2 control-label">Estado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["estado", "type" => "number", "class" => "form-control", "id" => "fieldEstado"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVehiculoplaca" class="col-sm-2 control-label">Vehiculo placa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["vehiculoplaca", "size" => 30, "class" => "form-control", "id" => "fieldVehiculoplaca"]); ?>
    </div>
</div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-success"]) ?>
        </div>
    </div>
</form>
