<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Buscar vehiculos</h1>
    <p><?php echo $this->tag->linkTo(["vehiculos/new", "Create vehiculos"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldPlaca" class="col-sm-2 control-label">Placa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["placa", "size" => 30, "class" => "form-control", "id" => "fieldPlaca"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMarca" class="col-sm-2 control-label">Marca</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["marca", "size" => 30, "class" => "form-control", "id" => "fieldMarca"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldModelo" class="col-sm-2 control-label">Modelo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["modelo", "size" => 30, "class" => "form-control", "id" => "fieldModelo"]); ?>
    </div>
</div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-success"]) ?>
        </div>
    </div>
</form>
